README.md
Reverts QkeleQ10/hypixel-translators-bot-discord#113
=> Revert "README edit"

commands/invite.js
Tier 3 invite doesn't work, updated invite to work.
=> +invite fixed invite

events/stats.js
Added more cases of "string(s)" and additionally added support for new/removed string notifications from the SBA project
=> SBA and string(s)

events/stats.js
Reverts QkeleQ10/hypixel-translators-bot-discord#130
=> Revert "Hopefully added sba language status?"

config.json
RIP Rodry, gone but not forgotten
=> added rodry

config.json
removed puggyxo and exy, added Deentrox
=> updated randomusers

config.json
removed HoggyTheWizard from RANDOMUSER
=> removed HoggyTheWizard

commands/help.js, commands/quote.js, strings/en/guidelines.json, strings/en/help.json, strings/en/hypixel.json, strings/en/quickplay.json
Brought the commits from the previous PR into this one, fixed !guide -> +guide and remove logging command.name from help.js. Also changed the "number" var in quote.js to add 1 instead of subtracting (so the row number gets logged properly instead of being 2 numbers below
=> Fix strings

commands/dm.js, commands/quote.js, commands/say.js, commands/updateinfo.js
This pr removes the permission override for any member and fixes out of place permissions
=> Removed perms

commands/ping.js, strings/en/ping.json
The color of the embed depends on the bots` latency.
Please test this before you merge this PR. I have tested this myself, but I'm unsure if this will actually work.
=> Ping command in embeds.

commands/mention.js
=> Improvements to +mention

index.js
For some reason, the font for the username was merged incorrectly. This should fix it.
=> fix font issues that arose when merging (?)

src/lib/dbclient.ts, src/listeners/message.ts, strings/en/global.json
**This PR:**
* was tested,
* **includes string changes.**
To change the time after you need to confirm the messages you send again **edit the const `timeToPass` on line 86 in `message.ts` and the appropriate strings in `global.json`**.
=> Staff messaging confirmation

src/commands/Info/levels.ts, strings/en/levels.json
Soo this pull request is very important, fix a major flaw in the potato farm and I think our production will increse after the merge (maybe +47%)
Nah I'm just kidding, I'm just lonely, I feel bad and I rly want a hug
Ow, beside my mental health being rly bad, this PR add a " - YOU" prefix on the levels page if it's you (:
- Strings were added/removed (new/deleted string keys)
=> Add "You-" as a prefix if it's you (:

src/commands/Utility/help.ts
Change the emojis to make them visible on any operation systems.
Please move lines that apply to you out of the comment:
=> Make help emojis compatible with other OSs

src/index.ts, src/listeners/messageCreate.ts
To make the message look more beautiful.
=> Use `message.reply` instance of pinging the user

src/commands/Staff/punishment.ts
Rodry ~~forced me~~ asked me to do this so here I am. Title is pretty self explanatory.
=> Disallow giving less points than the current active punishment has

src/lib/util.ts
Now when changing the language will be used correct string.
Please move lines that apply to you out of the comment:
=> Fix TIP being in the old language when changing langs

src/lib/dbclient.ts, src/listeners/guildMemberAdd.ts, src/listeners/guildMemberRemove.ts, src/listeners/interactionCreate.ts, src/listeners/messageCreate.ts, src/listeners/messageReactionAdd.ts, src/listeners/messageReactionRemove.ts
This PR (hopefully) fixes a bug that @ImRodry found, it's pretty well explained in the title.
=> Fix crash when accessing the db before initialization

src/commands/Utility/language.ts
=> fix(language): set option required

src/commands/Utility/languagestats.ts
Please describe the changes this PR makes and why it should be merged
After #570 the condition has become incorrect and the command throws an error even when my language is not English
In this PR:
Code changes were not tested
=> fix(languagestats): fix the condition

crowdin.yml
=> chore(crowdin): add pr title

src/commands/Utility/prefix.ts
Updates the logic in the prefix command to better comply with recent discord.js changes
=> refactor prefix logic

src/events/stats.ts
This PR fixes condition of Crowdin Updates ping
=> fix(stats): correct shouldPing condition

src/commands/Utility/languagestats.ts, src/lib/util.ts, src/listeners/interactionCreate.ts, src/listeners/messageCreate.ts, strings/en/languagestats.json
This PR fixes some strings number formats
- Strings were edited (text changed while the key stayed the same)
=> fix: fix number formats

src/commands/Utility/poll.ts, strings/en/poll.json
- Strings were added/removed (new/deleted string keys)
=> feat: use channelTypes option

src/commands/Utility/language.ts
This PR adds alphabetical sorting of language names
=> feat(language): sort names alphabetically

src/lib/crowdinverify.ts
This PR adds a notification for a user if they obtained a new veteran role.
=> feat: veteran roles notification
